name: Gradle Package Publish to Github Packages Repository

on:
  release:
    types: [published]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/settings.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          gradle-version: 8.5

      - name: Build Jar with Gradle
        run: ./gradlew :vault-connector:clean :vault-connector:jar --info --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_TAG: ${{ github.ref_name }}

      - name: List vault-connector/build/libs contents
        run: ls -la vault-connector/build/libs/

      - name: Publish to GitHub Packages
        run: ./gradlew :vault-connector:publish
        env:
          GITHUB_USERNAME: ${{ secrets.PACKAGE_PUBLISH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_PUBLISH_TOKEN }}
          GITHUB_TAG: ${{ github.ref_name }}
